=== annapowellsmith/openpresc/openprescribing/dmd/tests/fixtures/commands/gtin_v2_0.xsd
<?xml version="1.0"?>
<!-- Version 2.0 01/06/2013 GEBAW -->
<!-- Modified to allow an AMPP to have multiple GTIN Codes -->
<!-- Added mandatory start date and optional end date to each GTIN -->
<!-- Added simpleType GTINCode to ensure validation of GTIN as 13 or 14 characters -->
<!-- Changed GTINType to use GTINCode -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="AMPPType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="AMPPID" type="xs:integer" />
			<xs:element name="GTINDATA" type="GTINType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GTINType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="GTIN" type="GTINCode" minOccurs="1"  maxOccurs="1"/>
			<xs:element name="STARTDT" type="xs:date" minOccurs="1"  maxOccurs="1" />
			<xs:element name="ENDDT" type="xs:date" minOccurs="0"  maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="GTIN_DETAILS">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AMPPS">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AMPP" type="AMPPType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="GTINCode">
		<xs:restriction base="xs:string">
			<xs:pattern value="|([0-9]{13})|([0-9]{14})"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== annapowellsmith/openpresc/openprescribing/dmd/tests/fixtures/commands/f_gtin2_0280618.xml
<GTIN_DETAILS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gtin_v2_0.xsd">
  <!-- Generated by NHSBSA PPD on 2018/06/28 21:30:05 (and modified by gen_test_dmd_data.py) -->
  <AMPPS>
    <AMPP>
      <AMPPID>22479711000001106</AMPPID>
      <GTINDATA>
        <GTIN>5051562030603</GTIN>
        <STARTDT>2013-09-17</STARTDT>
      </GTINDATA>
    </AMPP>
    <AMPP>
      <AMPPID>22479911000001108</AMPPID>
      <GTINDATA>
        <GTIN>5051562030702</GTIN>
        <STARTDT>2013-09-17</STARTDT>
      </GTINDATA>
    </AMPP>
    <AMPP>
      <AMPPID>26352611000001103</AMPPID>
      <GTINDATA>
        <GTIN>5051562033802</GTIN>
        <STARTDT>2014-08-26</STARTDT>
      </GTINDATA>
    </AMPP>
    <AMPP>
      <AMPPID>35423511000001101</AMPPID>
      <GTINDATA>
        <GTIN>5055225061072</GTIN>
        <STARTDT>2018-05-08</STARTDT>
      </GTINDATA>
    </AMPP>
  </AMPPS>
</GTIN_DETAILS>
